unit testing file

diff --git a/.github/workflows/run-unit-test.yaml b/.github/workflows/run-unit-test.yaml
--- a/.github/workflows/run-unit-test.yaml
+++ b/.github/workflows/run-unit-test.yaml
@@ -39,20 +39,20 @@ jobs:
       - name: Execute Gradle build
         run: ./gradlew build
 
-      - name: Change US2Test Permissions
-        run: chmod +x ./src/test/US2Test.java
+      # - name: Change US2Test Permissions
+      #   run: chmod +x ./src/test/US2Test.java
 
-      - name: Build and Run Tests
-        run: javac src/test/US2Test.java
-        run: java src/test/US2Test
+      # - name: Build and Run Tests
+      #   run: javac src/test/US2Test.java
+      #   run: java src/test/US2Test
       
       - name: Unit tests
-        run: bash ./gradlew test --stacktrace
-      # report the results
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@v3
-        if: success() || failure() # always run even if the previous step fails
-        with:
-          report_paths: '**/build/test-results/test/TEST-*.xml'
-          detailed_summary: true # display detailed summary of the report
-          include_passed: true # include passed tests in the results table
+        run: ./gradlew test
+      # # report the results
+      # - name: Publish Test Report
+      #   uses: mikepenz/action-junit-report@v3
+      #   if: success() || failure() # always run even if the previous step fails
+      #   with:
+      #     report_paths: '**/build/test-results/test/TEST-*.xml'
+      #     detailed_summary: true # display detailed summary of the report
+      #     include_passed: true # include passed tests in the results table
